# Generated by Django 5.2.1 on 2025-05-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0002_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site setting', 'verbose_name_plural': 'Site settings'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
